name: transmission-daemon
version: git
version-script: git describe --tags HEAD
summary: Transmission is a fast, easy, and free BitTorrent client.
description: |
  Transmission is a BitTorrent client which features a variety 
  of user interfaces on top of a cross-platform back-end. 
  Transmission is free software licensed under the terms 
  of the GNU General Public License (GNU GPL), 
  with parts under the MIT License.
  This snap package has the daemon/CLI tools of Transmission

  Available config keys:
    - port:            listen port [9091]
    - dirs.downloads:  directory where files are downloaded
        [/var/snap/transmission-deamon/common/downloads]
    - dirs.watch:      directory to watch for torrent files [unset]
icon: gtk/icons/hicolor_apps_scalable_transmission.svg
base: core18
grade: stable
confinement: strict

apps:
  daemon:
    command: wrappers/daemon
    daemon: simple
    plugs:
      - network
      - network-bind
      - removable-media
  create:
    command: bin/transmission-create
    plugs:
      - home
      - removable-media
  edit:
    command: bin/transmission-edit
    plugs:
      - home
      - removable-media
  show:
    command: bin/transmission-show
    plugs:
      - home
      - removable-media
  remote:
    command: wrappers/remote
    plugs:
      - home
      - network
      - removable-media

parts:
  transmission-daemon:
    plugin: autotools
    source: .
    source-type: git
    configflags:
      - --disable-gtk
      - --enable-daemon
      - --disable-cli
    build-packages:
      - pkg-config
      - libcurl4-gnutls-dev
      - libevent-dev
      - zlib1g-dev
      - libssl-dev
      - intltool
      - libglib2.0-dev
      - libminiupnpc-dev
    stage-packages:
      - libcurl3
      - libcurl3-gnutls
      - libevent-2.1-6
      - libminiupnpc10
      # for configuration scripts
      - jq
      - libjq1
    stage:
      - bin
      - lib
      - share/transmission
      - usr/bin
      - usr/lib

  snap-data:
    plugin: dump
    source: snap-data
    stage:
      - wrappers
    prime:
      - wrappers
